/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static GUI.Venta.doc_cliente_txt;
/**
 *
 * @author SENA
 */
public class Buscar_Cliente extends javax.swing.JFrame {
private DefaultTableModel model;
    /**
     * Creates new form Busqueda_Clientes
     */
    public Buscar_Cliente() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
void busqueda(String valor) {
        int o = 0;
        try {

            Conexion con1 = new Conexion();
            con1.ConexionPostgres();
            String query = "select * from cliente WHERE CONCAT (cedula_cliente) LIKE '" + valor + "%' order by cedula_cliente";
            ResultSet rs5 = con1.consultar(query);
            ResultSetMetaData rsm = rs5.getMetaData();

            String data[][] = {};
            String[] col = new String[rsm.getColumnCount()];
            for (int i = 1; i <= rsm.getColumnCount(); i++) {
                col[i - 1] = rsm.getColumnName(i);

            }
            model = new DefaultTableModel(data, col);
            dtclientes.setModel(model);
            int x = 0;
            while (rs5.next()) {

               model.insertRow(x, new Object[]{}); //INSERTA FILA EN TIEMPO DE EJECUCION
                model.setValueAt(rs5.getLong("cedula_cliente"), x, 0);
                model.setValueAt(rs5.getString("primernombre_cliente"), x, 1);
                model.setValueAt(rs5.getString("segundonombre_cliente"), x, 2);
                model.setValueAt(rs5.getString("primerapellido_cliente"), x, 3);
                model.setValueAt(rs5.getString("segundoapellido_cliente"), x, 4);
                model.setValueAt(rs5.getLong("telefono_cliente"), x, 5);
                model.setValueAt(rs5.getString("correo_cliente"), x, 6);
                model.setValueAt(rs5.getString("direccion_cliente"), x, 7);
          
                x++;

            }

        } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dtclientes = new javax.swing.JTable();
        buscar2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        cedula_cliente = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        pnombre_cliente = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        snombre_cliente = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        telefono_cliente = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        Text11 = new javax.swing.JLabel();
        correo_cliente = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        papellido_cliente = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        sapellido_cliente = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btnagregar = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JLabel();
        btneditar = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        direccion_cliente = new javax.swing.JTextField();
        Text12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dtclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtclientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dtclientes);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 775, 412));

        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });
        buscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscar2KeyTyped(evt);
            }
        });
        jPanel3.add(buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 30));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Buscar por Cedula Cliente");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 50));

        jTabbedPane1.addTab("Buscar Cliente", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 40));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Agregar, Buscar, Modificar y Mostrar Clientes");
        jPanel2.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 620, -1));

        cedula_cliente.setForeground(new java.awt.Color(102, 102, 102));
        cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
        cedula_cliente.setBorder(null);
        cedula_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedula_clienteMousePressed(evt);
            }
        });
        cedula_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula_clienteActionPerformed(evt);
            }
        });
        cedula_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedula_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(cedula_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 330, 30));

        jSeparator10.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 280, 10));

        Text9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text9.setText("Numero de Documento");
        jPanel2.add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 180, -1));

        Text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text3.setText("Primer Nombre ");
        jPanel2.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        pnombre_cliente.setForeground(new java.awt.Color(102, 102, 102));
        pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
        pnombre_cliente.setBorder(null);
        pnombre_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnombre_clienteMousePressed(evt);
            }
        });
        pnombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnombre_clienteActionPerformed(evt);
            }
        });
        pnombre_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnombre_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(pnombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 300, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 250, 10));

        Text6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text6.setText("Segundo Nombre");
        jPanel2.add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, -1));

        snombre_cliente.setForeground(new java.awt.Color(102, 102, 102));
        snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
        snombre_cliente.setBorder(null);
        snombre_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                snombre_clienteMousePressed(evt);
            }
        });
        snombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snombre_clienteActionPerformed(evt);
            }
        });
        snombre_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snombre_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(snombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 30));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 250, 10));

        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 280, 10));

        telefono_cliente.setForeground(new java.awt.Color(102, 102, 102));
        telefono_cliente.setText("Ingrese el Telefono del Cliente");
        telefono_cliente.setBorder(null);
        telefono_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telefono_clienteMousePressed(evt);
            }
        });
        telefono_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_clienteActionPerformed(evt);
            }
        });
        telefono_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 330, 30));

        Text4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text4.setText("Telefono");
        jPanel2.add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 110, -1));

        Text11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text11.setText("Correo Electrónico");
        jPanel2.add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 180, -1));

        correo_cliente.setForeground(new java.awt.Color(102, 102, 102));
        correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
        correo_cliente.setBorder(null);
        correo_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correo_clienteMousePressed(evt);
            }
        });
        correo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(correo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 330, 30));

        Text7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text7.setText("Primer Apellido");
        jPanel2.add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, -1));

        papellido_cliente.setForeground(new java.awt.Color(102, 102, 102));
        papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
        papellido_cliente.setBorder(null);
        papellido_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                papellido_clienteMousePressed(evt);
            }
        });
        papellido_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papellido_clienteActionPerformed(evt);
            }
        });
        papellido_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                papellido_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(papellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 250, 30));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 10));

        Text8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text8.setText("Segundo Apellido");
        jPanel2.add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, -1));

        sapellido_cliente.setForeground(new java.awt.Color(102, 102, 102));
        sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
        sapellido_cliente.setBorder(null);
        sapellido_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sapellido_clienteMousePressed(evt);
            }
        });
        sapellido_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapellido_clienteActionPerformed(evt);
            }
        });
        sapellido_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sapellido_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(sapellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 250, 30));

        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 250, 10));

        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnadduser.png"))); // NOI18N
        btnagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMouseClicked(evt);
            }
        });
        jPanel2.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnbuscar.png"))); // NOI18N
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnedit.png"))); // NOI18N
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditarMouseClicked(evt);
            }
        });
        jPanel2.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 280, 10));

        direccion_cliente.setForeground(new java.awt.Color(102, 102, 102));
        direccion_cliente.setText("Ingrese la Dirección del Cliente");
        direccion_cliente.setBorder(null);
        direccion_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                direccion_clienteMousePressed(evt);
            }
        });
        direccion_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(direccion_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 330, 30));

        Text12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text12.setText("Dirección");
        jPanel2.add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 140, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 10, 290));

        jSeparator12.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 280, 10));

        jTabbedPane1.addTab("Agregar Cliente", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar2ActionPerformed

    private void buscar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar2KeyReleased
        busqueda(buscar2.getText());
    }//GEN-LAST:event_buscar2KeyReleased

    private void buscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar2KeyTyped

    private void dtclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtclientesMouseClicked
    
    }//GEN-LAST:event_dtclientesMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(dtclientes.getSelectedRow()>=0 ){
            doc_cliente_txt.setText(String.valueOf(Long.parseLong(dtclientes.getValueAt(dtclientes.getSelectedRow(), 0).toString())));
            doc_cliente_txt.setForeground(Color.black);
            this.dispose();
        }else{
            int rpta = JOptionPane.showConfirmDialog(this, "NO A ELEJIDO NINGÚN CLIENTE, ¿DESEAS CERRAR LA BUSQUEDA RAPIDA?","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
            if(rpta == JOptionPane.YES_OPTION){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void cedula_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedula_clienteMousePressed
        if (cedula_cliente.getText().equals("Ingrese el Numero de Documento del Cliente")) {
            cedula_cliente.setText("");
            cedula_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cedula_clienteMousePressed

    private void cedula_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedula_clienteActionPerformed

    private void cedula_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedula_clienteKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_cedula_clienteKeyTyped

    private void pnombre_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnombre_clienteMousePressed
        if (pnombre_cliente.getText().equals("Ingrese el Primer Nombre del Cliente")) {
            pnombre_cliente.setText("");
            pnombre_cliente.setForeground(Color.black);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pnombre_clienteMousePressed

    private void pnombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnombre_clienteActionPerformed

    private void pnombre_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnombre_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_pnombre_clienteKeyTyped

    private void snombre_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snombre_clienteMousePressed
        if (snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente")) {
            snombre_cliente.setText("");
            snombre_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_snombre_clienteMousePressed

    private void snombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snombre_clienteActionPerformed

    private void snombre_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snombre_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_snombre_clienteKeyTyped

    private void telefono_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_clienteMousePressed
        if (telefono_cliente.getText().equals("Ingrese el Telefono del Cliente")) {
            telefono_cliente.setText("");
            telefono_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_telefono_clienteMousePressed

    private void telefono_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_clienteActionPerformed

    private void telefono_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_clienteKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_telefono_clienteKeyTyped

    private void correo_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correo_clienteMousePressed
        if (correo_cliente.getText().equals("Ingrese el Correo Electronico del Cliente")) {
            correo_cliente.setText("");
            correo_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_correo_clienteMousePressed

    private void correo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_clienteActionPerformed

    private void papellido_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papellido_clienteMousePressed
        if (papellido_cliente.getText().equals("Ingrese el Primer Apellido del Cliente")) {
            papellido_cliente.setText("");
            papellido_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_papellido_clienteMousePressed

    private void papellido_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papellido_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_papellido_clienteActionPerformed

    private void papellido_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papellido_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_papellido_clienteKeyTyped

    private void sapellido_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapellido_clienteMousePressed
        if (sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente")) {
            sapellido_cliente.setText("");
            sapellido_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_sapellido_clienteMousePressed

    private void sapellido_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapellido_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_clienteActionPerformed

    private void sapellido_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapellido_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_sapellido_clienteKeyTyped

    private void btnagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseClicked
        try {
            // TODO add your handling code here:

            Conexion con = new Conexion();
            con.ConexionPostgres();

            if(correo_cliente.getText().contains("@") && correo_cliente.getText().contains(".")){
                if(telefono_cliente.getText().length()==10){
                    if(snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente") && sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente")){
                        String query = "INSERT INTO cliente VALUES ("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','','"+papellido_cliente.getText().trim()+"','',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);

                        con.cerrar();
                        cedula_cliente.setText(null);
                        pnombre_cliente.setText(null);
                        snombre_cliente.setText(null);
                        papellido_cliente.setText(null);
                        sapellido_cliente.setText(null);
                        telefono_cliente.setText(null);
                        correo_cliente.setText(null);
                        direccion_cliente.setText(null);
                    }
                    else if(snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente")){
                        String query = "INSERT INTO cliente VALUES ("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','"+papellido_cliente.getText().trim()+"','"+sapellido_cliente.getText().trim()+"',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);

                        con.cerrar();
                        cedula_cliente.setText(null);
                        pnombre_cliente.setText(null);
                        snombre_cliente.setText(null);
                        papellido_cliente.setText(null);
                        sapellido_cliente.setText(null);
                        telefono_cliente.setText(null);
                        correo_cliente.setText(null);
                        direccion_cliente.setText(null);
                    }
                    else if(sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del cliente")){
                        String query = "INSERT INTO empleado VALUES ("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','"+snombre_cliente.getText().trim()+"','"+papellido_cliente.getText().trim()+"',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);

                        con.cerrar();
                        cedula_cliente.setText(null);
                        pnombre_cliente.setText(null);
                        snombre_cliente.setText(null);
                        papellido_cliente.setText(null);
                        sapellido_cliente.setText(null);
                        telefono_cliente.setText(null);
                        correo_cliente.setText(null);
                        direccion_cliente.setText(null);
                    }
                    else{
                        String query = "INSERT INTO cliente VALUES ("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','"+snombre_cliente.getText().trim()+"','"+papellido_cliente.getText().trim()+"','"+sapellido_cliente.getText().trim()+"',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);

                        con.cerrar();
                        cedula_cliente.setText(null);
                        pnombre_cliente.setText(null);
                        snombre_cliente.setText(null);
                        papellido_cliente.setText(null);
                        sapellido_cliente.setText(null);
                        telefono_cliente.setText(null);
                        correo_cliente.setText(null);
                        direccion_cliente.setText(null);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Telefono Invalido!");
                }

            }
            else{
                JOptionPane.showMessageDialog(this, "Correo Invalido!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnagregarMouseClicked

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        try {
            // TODO add your handling code here:

            Conexion con = new Conexion();
            con.ConexionPostgres();

            String query ="select * from cliente where cedula_cliente = "+ Long.parseLong(cedula_cliente.getText().trim());
            ResultSet rs = con.consultar(query);

            if(rs.next()){
                pnombre_cliente.setText(rs.getString("primernombre_cliente"));
                snombre_cliente.setText(rs.getString("segundonombre_cliente"));
                papellido_cliente.setText(rs.getString("primerapellido_cliente"));
                sapellido_cliente.setText(rs.getString("segundoapellido_cliente"));
                telefono_cliente.setText(rs.getString("telefono_cliente"));
                correo_cliente.setText(rs.getString("correo_cliente"));
                direccion_cliente.setText(rs.getString("direccion_cliente"));
            }

            else{
                JOptionPane.showMessageDialog(this, "No existe el Cliente");
            }
            pnombre_cliente.setForeground(Color.black);
            snombre_cliente.setForeground(Color.black);
            papellido_cliente.setForeground(Color.black);
            sapellido_cliente.setForeground(Color.black);
            correo_cliente.setForeground(Color.black);
            telefono_cliente.setForeground(Color.black);
            direccion_cliente.setForeground(Color.black);
            con.cerrar();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnbuscarMouseClicked

    private void btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditarMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();

            String query = "UPDATE cliente SET pnombre_cliente = '"+pnombre_cliente.getText().trim()+"',snombre_cliente = '"+snombre_cliente.getText().trim()+"', papellido_cliente = '"+papellido_cliente.getText().trim()+"', sapellido_cliente = '"+sapellido_cliente.getText().trim()+"', telefono_cliente = "+Long.parseLong(telefono_cliente.getText().trim())+", correo_cliente = '"+correo_cliente.getText().trim()+"', direccion_cliente = '"+direccion_cliente.getText().trim()+"' WHERE cedula_cliente = "+Long.parseLong(cedula_cliente.getText().trim())+"";
            JOptionPane.showMessageDialog(this, "Datos Actualizaos Correctamente!");
            con.actualizar(query);

            con.cerrar();
            cedula_cliente.setText(null);
            pnombre_cliente.setText(null);
            snombre_cliente.setText(null);
            papellido_cliente.setText(null);
            sapellido_cliente.setText(null);
            telefono_cliente.setText(null);
            correo_cliente.setText(null);
            direccion_cliente.setText(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(clientevista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditarMouseClicked

    private void direccion_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccion_clienteMousePressed
        if (direccion_cliente.getText().equals("Ingrese la Dirección del Cliente")) {
            direccion_cliente.setText("");
            direccion_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_direccion_clienteMousePressed

    private void direccion_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel btnagregar;
    private javax.swing.JLabel btnbuscar;
    private javax.swing.JLabel btneditar;
    private javax.swing.JTextField buscar2;
    private javax.swing.JTextField cedula_cliente;
    private javax.swing.JTextField correo_cliente;
    private javax.swing.JTextField direccion_cliente;
    public static javax.swing.JTable dtclientes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField papellido_cliente;
    private javax.swing.JTextField pnombre_cliente;
    private javax.swing.JTextField sapellido_cliente;
    private javax.swing.JTextField snombre_cliente;
    private javax.swing.JTextField telefono_cliente;
    // End of variables declaration//GEN-END:variables
}
