/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static GUI.Venta.doc_cliente_txt;
/**
 *
 * @author SENA
 */
public class Buscar_Cliente extends javax.swing.JFrame {
private DefaultTableModel model;
    /**
     * Creates new form Busqueda_Clientes
     */
    public Buscar_Cliente() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
void busqueda(String valor) {
        int o = 0;
        try {

            Conexion con1 = new Conexion();
            con1.ConexionPostgres();
            String query = "select * from cliente WHERE CONCAT (cedula_cliente) LIKE '" + valor + "%' order by cedula_cliente";
            ResultSet rs5 = con1.consultar(query);
            ResultSetMetaData rsm = rs5.getMetaData();

            String data[][] = {};
            String[] col = new String[rsm.getColumnCount()];
            for (int i = 1; i <= rsm.getColumnCount(); i++) {
                col[i - 1] = rsm.getColumnName(i);

            }
            model = new DefaultTableModel(data, col);
            dtclientes.setModel(model);
            int x = 0;
            while (rs5.next()) {

               model.insertRow(x, new Object[]{}); //INSERTA FILA EN TIEMPO DE EJECUCION
                model.setValueAt(rs5.getLong("cedula_cliente"), x, 0);
                model.setValueAt(rs5.getString("primernombre_cliente"), x, 1);
                model.setValueAt(rs5.getString("segundonombre_cliente"), x, 2);
                model.setValueAt(rs5.getString("primerapellido_cliente"), x, 3);
                model.setValueAt(rs5.getString("segundoapellido_cliente"), x, 4);
                model.setValueAt(rs5.getLong("telefono_cliente"), x, 5);
                model.setValueAt(rs5.getString("correo_cliente"), x, 6);
                model.setValueAt(rs5.getString("direccion_cliente"), x, 7);
          
                x++;

            }

        } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dtclientes = new javax.swing.JTable();
        buscar2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Text3 = new javax.swing.JLabel();
        pnombre_cliente = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        snombre_cliente = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        papellido_cliente = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        sapellido_cliente = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        direccion_cliente = new javax.swing.JTextField();
        Text12 = new javax.swing.JLabel();
        correo_cliente = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Text11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        telefono_cliente = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        cedula_cliente = new javax.swing.JTextField();
        Text9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        agregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        button7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        modificar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        button15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dtclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtclientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dtclientes);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 775, 412));

        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });
        buscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscar2KeyTyped(evt);
            }
        });
        jPanel3.add(buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 30));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Buscar por Cedula Cliente");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 50, 50));

        jTabbedPane1.addTab("Buscar Cliente", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Primer Nombre ");
        jPanel2.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, -1));

        pnombre_cliente.setForeground(new java.awt.Color(102, 102, 102));
        pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
        pnombre_cliente.setBorder(null);
        pnombre_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnombre_clienteMousePressed(evt);
            }
        });
        pnombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnombre_clienteActionPerformed(evt);
            }
        });
        pnombre_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnombre_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(pnombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 330, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Segundo Nombre");
        jPanel2.add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        snombre_cliente.setForeground(new java.awt.Color(102, 102, 102));
        snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
        snombre_cliente.setBorder(null);
        snombre_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                snombre_clienteMousePressed(evt);
            }
        });
        snombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snombre_clienteActionPerformed(evt);
            }
        });
        snombre_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snombre_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(snombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 330, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Primer Apellido");
        jPanel2.add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, -1));

        papellido_cliente.setForeground(new java.awt.Color(102, 102, 102));
        papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
        papellido_cliente.setBorder(null);
        papellido_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                papellido_clienteMousePressed(evt);
            }
        });
        papellido_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papellido_clienteActionPerformed(evt);
            }
        });
        papellido_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                papellido_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(papellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 330, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 330, 10));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Segundo Apellido");
        jPanel2.add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, -1));

        sapellido_cliente.setForeground(new java.awt.Color(102, 102, 102));
        sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
        sapellido_cliente.setBorder(null);
        sapellido_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sapellido_clienteMousePressed(evt);
            }
        });
        sapellido_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapellido_clienteActionPerformed(evt);
            }
        });
        sapellido_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sapellido_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(sapellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 330, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 330, 10));

        jSeparator13.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 330, 10));

        direccion_cliente.setForeground(new java.awt.Color(102, 102, 102));
        direccion_cliente.setText("Ingrese la Dirección del Cliente");
        direccion_cliente.setBorder(null);
        direccion_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                direccion_clienteMousePressed(evt);
            }
        });
        direccion_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(direccion_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 330, 30));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("Dirección");
        jPanel2.add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 140, -1));

        correo_cliente.setForeground(new java.awt.Color(102, 102, 102));
        correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
        correo_cliente.setBorder(null);
        correo_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correo_clienteMousePressed(evt);
            }
        });
        correo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(correo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 330, 30));

        jSeparator12.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 330, 10));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Correo Electrónico");
        jPanel2.add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 180, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 330, 10));

        telefono_cliente.setForeground(new java.awt.Color(102, 102, 102));
        telefono_cliente.setText("Ingrese el Telefono del Cliente");
        telefono_cliente.setBorder(null);
        telefono_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telefono_clienteMousePressed(evt);
            }
        });
        telefono_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_clienteActionPerformed(evt);
            }
        });
        telefono_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 330, 30));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Telefono");
        jPanel2.add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 110, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 330, 10));

        cedula_cliente.setForeground(new java.awt.Color(102, 102, 102));
        cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
        cedula_cliente.setBorder(null);
        cedula_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedula_clienteMousePressed(evt);
            }
        });
        cedula_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula_clienteActionPerformed(evt);
            }
        });
        cedula_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedula_clienteKeyTyped(evt);
            }
        });
        jPanel2.add(cedula_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 330, 30));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Numero de Documento");
        jPanel2.add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 180, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 10, 290));

        agregar.setBackground(new java.awt.Color(0, 204, 51));
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarMousePressed(evt);
            }
        });
        agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar");
        agregar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button3.setBackground(new java.awt.Color(0, 204, 51));
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button3MousePressed(evt);
            }
        });
        button3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar");
        button3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        agregar.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        jPanel2.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, 50));

        buscar.setBackground(new java.awt.Color(0, 204, 51));
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        buscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        buscar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 90, 30));

        button1.setBackground(new java.awt.Color(0, 204, 51));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar");
        button1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        buscar.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        button4.setBackground(new java.awt.Color(0, 204, 51));
        button4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button4MousePressed(evt);
            }
        });
        button4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar");
        button4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button5.setBackground(new java.awt.Color(0, 204, 51));
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button5MousePressed(evt);
            }
        });
        button5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agregar");
        button5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        button4.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        buscar.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 140, 50));

        button6.setBackground(new java.awt.Color(0, 204, 51));
        button6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button6MousePressed(evt);
            }
        });
        button6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Agregar");
        button6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button7.setBackground(new java.awt.Color(0, 204, 51));
        button7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button7MousePressed(evt);
            }
        });
        button7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Agregar");
        button7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        button6.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        buscar.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 50));

        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 150, 50));

        modificar.setBackground(new java.awt.Color(0, 204, 51));
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarMousePressed(evt);
            }
        });
        modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Modificar");
        modificar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 90, 30));

        button15.setBackground(new java.awt.Color(0, 204, 51));
        button15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button15MousePressed(evt);
            }
        });
        button15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Agregar");
        button15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        modificar.add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        jPanel2.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 150, 50));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Agregar, Buscar y Modificar Clientes");
        jPanel2.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 720, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 40));

        jTabbedPane1.addTab("Agregar Cliente", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar2ActionPerformed

    private void buscar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar2KeyReleased
        busqueda(buscar2.getText());
    }//GEN-LAST:event_buscar2KeyReleased

    private void buscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar2KeyTyped

    private void pnombre_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnombre_clienteMousePressed
        if (pnombre_cliente.getText().equals("Ingrese el Primer Nombre del Cliente")) {
            pnombre_cliente.setText("");
            pnombre_cliente.setForeground(Color.black);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pnombre_clienteMousePressed

    private void pnombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnombre_clienteActionPerformed

    private void pnombre_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnombre_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'á' || c<'ú') && (c<'Á' || c<'Ú') && c<'ñ' && c<'Ñ') evt.consume();
    }//GEN-LAST:event_pnombre_clienteKeyTyped

    private void snombre_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snombre_clienteMousePressed
        if (snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente")) {
            snombre_cliente.setText("");
            snombre_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_snombre_clienteMousePressed

    private void snombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snombre_clienteActionPerformed

    private void snombre_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snombre_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'á' || c<'ú') && (c<'Á' || c<'Ú') && c<'ñ' && c<'Ñ') evt.consume();
    }//GEN-LAST:event_snombre_clienteKeyTyped

    private void papellido_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papellido_clienteMousePressed
        if (papellido_cliente.getText().equals("Ingrese el Primer Apellido del Cliente")) {
            papellido_cliente.setText("");
            papellido_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_papellido_clienteMousePressed

    private void papellido_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papellido_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_papellido_clienteActionPerformed

    private void papellido_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papellido_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'á' || c<'ú') && (c<'Á' || c<'Ú') && c<'ñ' && c<'Ñ') evt.consume();
    }//GEN-LAST:event_papellido_clienteKeyTyped

    private void sapellido_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapellido_clienteMousePressed
        if (sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente")) {
            sapellido_cliente.setText("");
            sapellido_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_sapellido_clienteMousePressed

    private void sapellido_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapellido_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_clienteActionPerformed

    private void sapellido_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapellido_clienteKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<'á' || c<'ú') && (c<'Á' || c<'Ú') && c<'ñ' && c<'Ñ') evt.consume();
    }//GEN-LAST:event_sapellido_clienteKeyTyped

    private void direccion_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccion_clienteMousePressed
        if (direccion_cliente.getText().equals("Ingrese la Dirección del Cliente")) {
            direccion_cliente.setText("");
            direccion_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_direccion_clienteMousePressed

    private void direccion_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_clienteActionPerformed

    private void correo_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correo_clienteMousePressed
        if (correo_cliente.getText().equals("Ingrese el Correo Electronico del Cliente")) {
            correo_cliente.setText("");
            correo_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_correo_clienteMousePressed

    private void correo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_clienteActionPerformed

    private void telefono_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_clienteMousePressed
        if (telefono_cliente.getText().equals("Ingrese el Telefono del Cliente")) {
            telefono_cliente.setText("");
            telefono_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (cedula_cliente.getText().isEmpty()) {
            cedula_cliente.setText("Ingrese el Numero de Documento del Cliente");
            cedula_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_telefono_clienteMousePressed

    private void telefono_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_clienteActionPerformed

    private void telefono_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_clienteKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_telefono_clienteKeyTyped

    private void cedula_clienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedula_clienteMousePressed
        if (cedula_cliente.getText().equals("Ingrese el Numero de Documento del Cliente")) {
            cedula_cliente.setText("");
            cedula_cliente.setForeground(Color.black);
        }

        if (pnombre_cliente.getText().isEmpty()) {
            pnombre_cliente.setText("Ingrese el Primer Nombre del Cliente");
            pnombre_cliente.setForeground(Color.gray);
        }

        if (snombre_cliente.getText().isEmpty()) {
            snombre_cliente.setText("Ingrese el Segundo Nombre del Cliente");
            snombre_cliente.setForeground(Color.gray);
        }

        if (sapellido_cliente.getText().isEmpty()) {
            sapellido_cliente.setText("Ingrese el Segundo Apellido del Cliente");
            sapellido_cliente.setForeground(Color.gray);
        }

        if (papellido_cliente.getText().isEmpty()) {
            papellido_cliente.setText("Ingrese el Primer Apellido del Cliente");
            papellido_cliente.setForeground(Color.gray);
        }

        if (telefono_cliente.getText().isEmpty()) {
            telefono_cliente.setText("Ingrese el Telefono del Cliente");
            telefono_cliente.setForeground(Color.gray);
        }

        if (correo_cliente.getText().isEmpty()) {
            correo_cliente.setText("Ingrese el Correo Electronico del Cliente");
            correo_cliente.setForeground(Color.gray);
        }

        if (direccion_cliente.getText().isEmpty()) {
            direccion_cliente.setText("Ingrese la Dirección del Cliente");
            direccion_cliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cedula_clienteMousePressed

    private void cedula_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedula_clienteActionPerformed

    private void cedula_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedula_clienteKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_cedula_clienteKeyTyped

    private void button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button3MouseEntered

    private void button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button3MouseExited

    private void button3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3MousePressed

    private void agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseEntered
        agregar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_agregarMouseEntered

    private void agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseExited
        agregar.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_agregarMouseExited

    private void agregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMousePressed
        
        try {
            Conexion con = new Conexion(); //CREO CON PARA HACER LA CONEXION, CONSULTAS, MODIFICACIONES
            con.ConexionPostgres(); //CONECTO A LA BASE DE DATOS
            if(correo_cliente.getText().contains("@") && correo_cliente.getText().contains(".")){ //VALIDACION PARA QUE EL CORREO TENGA (@ Y .) CON EL .CONTAINS
                if(telefono_cliente.getText().length()==10){ //VALIDACION PARA QUE EL CAMPO DE TELEFONO TENGO 10 DIGITOS
                    if((snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente") || snombre_cliente.getText().equals("")) && (sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente") || sapellido_cliente.getText().equals(""))){ //VALIDACION PARA QUE AGREGUE EN BLANCO EL SEGUNDO NOMBRE Y EL SEGUNDO APELLIDO
                        String query ="insert into cliente values("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','','"+papellido_cliente.getText().trim()+"','',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')"; //LINEA PARA LA INSERSION DE DATOS
                        JOptionPane.showMessageDialog(this, "Registro exitoso"); //MENSAJE DE REGISTRO
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                    }
                    else if(snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente") || snombre_cliente.getText().equals("")){ //VALIDACION PARA QUE AGREGUE EN BLANCO EL SEGUNDO NOMBRE
                        String query ="insert into cliente values("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','','"+papellido_cliente.getText().trim()+"','"+sapellido_cliente.getText().trim()+"',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')"; //LINEA PARA LA INSERSION DE DATOS
                        JOptionPane.showMessageDialog(this, "Registro exitoso"); //MENSAJE DE REGISTRO
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                    }
                    else if(sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente") || sapellido_cliente.getText().equals("")){ //VALIDACION PARA QUE AGREGUE EN BLANCO EL SEGUNDO APELLIDO
                        String query ="insert into cliente values("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','"+snombre_cliente.getText().trim()+"','"+papellido_cliente.getText().trim()+"','',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')"; //LINEA PARA LA INSERSION DE DATOS
                        JOptionPane.showMessageDialog(this, "Registro exitoso"); //MENSAJE DE REGISTRO
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                    }
                    else { //VALIDACION PARA QUE AGREGUE TODOS LOS CAMPOS
                        String query ="insert into cliente values("+Long.parseLong(cedula_cliente.getText().trim())+",'"+pnombre_cliente.getText().trim()+"','"+snombre_cliente.getText().trim()+"','"+papellido_cliente.getText().trim()+"','"+sapellido_cliente.getText().trim()+"',"+Long.parseLong(telefono_cliente.getText().trim())+",'"+correo_cliente.getText().trim()+"','"+direccion_cliente.getText().trim()+"')"; //LINEA PARA LA INSERSION DE DATOS
                        JOptionPane.showMessageDialog(this, "Registro exitoso"); //MENSAJE DE REGISTRO
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS

                    }
                }
                else{ //CONDICION POR SI NO SE CUMPLE LA VALIDACION DEL TELEFONO
                    JOptionPane.showMessageDialog(this, "Telefono Invalido"); //MENSAJE DE TELEFONO INVALIDO CUANDO LA VALIDACION NO SE CUMPLE
                }
            }
            else{ //CONDICION POR SI NO SE CUMPLE LA VALIDACION DE CORREO
                JOptionPane.showMessageDialog(this, "Correo Invalido"); //MENSAJE DE CORREO INVALIDO CUANDO LA VALIDACION NO SE CUMPLE
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_agregarMousePressed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MousePressed

    private void button5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button5MouseEntered

    private void button5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button5MouseExited

    private void button5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5MousePressed

    private void button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button4MouseEntered

    private void button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button4MouseExited

    private void button4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4MousePressed

    private void button7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button7MouseEntered

    private void button7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button7MouseExited

    private void button7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7MousePressed

    private void button6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button6MouseEntered

    private void button6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button6MouseExited

    private void button6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6MousePressed

    private void buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseEntered
        buscar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_buscarMouseEntered

    private void buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseExited
        buscar.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_buscarMouseExited

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        
        try {
            Conexion con = new Conexion(); //CREO CON PARA HACER LA CONEXION, CONSULTAS, MODIFICACIONES
            con.ConexionPostgres(); //CONECTO A LA BASE DE DATOS

            String query ="select * from cliente where cedula_cliente = "+ Long.parseLong(cedula_cliente.getText().trim()); //LINEA PARA LA BUSQUEDA DE DATOS

            ResultSet rs = con.consultar(query); //CREO RS PARA HACER LA CONSULTA EN LA BASE DE DATOS

            if(rs.next()){ //CONDICION PARA CONFIRMAR QUE EXISTE EL CLIENTE
                pnombre_cliente.setText(rs.getString("primernombre_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
                snombre_cliente.setText(rs.getString("segundonombre_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
                papellido_cliente.setText(rs.getString("primerapellido_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
                sapellido_cliente.setText(rs.getString("segundoapellido_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
                telefono_cliente.setText(rs.getString("telefono_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
                correo_cliente.setText(rs.getString("correo_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
                direccion_cliente.setText(rs.getString("direccion_cliente")); //ESCRIBE EL DATO RESPECTIVO DEL CLIENTE DE LA TABLA EN EL JTEXTFIELD INDICADO
            }

            else{ //CONDICON POR SI NO SE CONFIRMA LA EXITENCIA DEL CLIENTE
                JOptionPane.showMessageDialog(this, "No existe el Cliente"); //MENSAJE DE CONSULTA FALSA
            }
            pnombre_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            snombre_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            papellido_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            sapellido_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            correo_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            telefono_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            direccion_cliente.setForeground(Color.black); //LA LETRA DEL CAMPO SEA NEGRA(BLACK)
            con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buscarMousePressed

    private void button15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseEntered

    private void button15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseExited

    private void button15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MousePressed

    private void modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseEntered
        modificar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_modificarMouseEntered

    private void modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseExited
        modificar.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_modificarMouseExited

    private void modificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMousePressed
        
        try {
            Conexion con = new Conexion(); //CREO CON PARA HACER LA CONEXION, CONSULTAS, MODIFICACIONES
            con.ConexionPostgres(); //CONECTO A LA BASE DE DATOS
            if(correo_cliente.getText().contains("@") && correo_cliente.getText().contains(".")){ //VALIDACION PARA QUE EL CORREO TENGA (@ Y .) CON EL .CONTAINS
                if(telefono_cliente.getText().length()==10){ //VALIDACION PARA QUE EL CAMPO DE TELEFONO TENGO 10 DIGITOS
                    if((snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente") || snombre_cliente.getText().equals("")) && (sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente") || sapellido_cliente.getText().equals(""))){ //VALIDACION PARA QUE AGREGUE EN BLANCO EL SEGUNDO NOMBRE Y EL SEGUNDO APELLIDO
                        String query ="update cliente set primernombre_cliente = '"+pnombre_cliente.getText().trim()+"', segundonombre_cliente='', primerapellido_cliente='"+papellido_cliente.getText().trim()+"', segundoapellido_cliente='', telefono_cliente="+Long.parseLong(telefono_cliente.getText().trim())+",correo_cliente='"+correo_cliente.getText().trim()+"', direccion_cliente='"+direccion_cliente.getText().trim()+"'where cedula_cliente="+Long.parseLong(cedula_cliente.getText().trim()); //LINEA PARA LA ACTUALIZACION DE DATOS
                        JOptionPane.showMessageDialog(this, "Datos Actualizados"); //MENSAJE DE ACTUALIZACION
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                    }
                    else if(snombre_cliente.getText().equals("Ingrese el Segundo Nombre del Cliente") || snombre_cliente.getText().equals("")){ //VALIDACION PARA QUE AGREGUE EN BLANCO EL SEGUNDO NOMBRE
                        String query ="update cliente set primernombre_cliente = '"+pnombre_cliente.getText().trim()+"', segundonombre_cliente='', primerapellido_cliente='"+papellido_cliente.getText().trim()+"', segundoapellido_cliente='"+sapellido_cliente.getText().trim()+"', telefono_cliente="+Long.parseLong(telefono_cliente.getText().trim())+",correo_cliente='"+correo_cliente.getText().trim()+"', direccion_cliente='"+direccion_cliente.getText().trim()+"'where cedula_cliente="+Long.parseLong(cedula_cliente.getText().trim()); //LINEA PARA LA ACTUALIZACION DE DATOS
                        JOptionPane.showMessageDialog(this, "Datos Actualizados"); //MENSAJE DE ACTUALIZACION
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                    }
                    else if(sapellido_cliente.getText().equals("Ingrese el Segundo Apellido del Cliente") || sapellido_cliente.getText().equals("")){ //VALIDACION PARA QUE AGREGUE EN BLANCO EL SEGUNDO APELLIDO
                        String query ="update cliente set primernombre_cliente = '"+pnombre_cliente.getText().trim()+"', segundonombre_cliente='"+snombre_cliente.getText().trim()+"', primerapellido_cliente='"+papellido_cliente.getText().trim()+"', segundoapellido_cliente='', telefono_cliente="+Long.parseLong(telefono_cliente.getText().trim())+",correo_cliente='"+correo_cliente.getText().trim()+"', direccion_cliente='"+direccion_cliente.getText().trim()+"'where cedula_cliente="+Long.parseLong(cedula_cliente.getText().trim()); //LINEA PARA LA ACTUALIZACION DE DATOS
                        JOptionPane.showMessageDialog(this, "Datos Actualizados"); //MENSAJE DE ACTUALIZACION
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                    }
                    else { //VALIDACION PARA QUE AGREGUE TODOS LOS CAMPOS
                        String query ="update cliente set primernombre_cliente = '"+pnombre_cliente.getText().trim()+"', segundonombre_cliente='"+snombre_cliente.getText().trim()+"', primerapellido_cliente='"+papellido_cliente.getText().trim()+"', segundoapellido_cliente='"+sapellido_cliente.getText().trim()+"', telefono_cliente="+Long.parseLong(telefono_cliente.getText().trim())+",correo_cliente='"+correo_cliente.getText().trim()+"', direccion_cliente='"+direccion_cliente.getText().trim()+"'where cedula_cliente="+Long.parseLong(cedula_cliente.getText().trim()); //LINEA PARA LA ACTUALIZACION DE DATOS
                        JOptionPane.showMessageDialog(this, "Datos Actualizados"); //MENSAJE DE ACTUALIZACION
                        con.actualizar(query); //ACTUALIZACION DE DATOS EN LA BASE DE DATOS

                        con.cerrar(); //CIERRE DE CONEXION A LA BASE DE DATOS
                        pnombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        snombre_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        papellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        sapellido_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        cedula_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        correo_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        direccion_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS
                        telefono_cliente.setText(null); //COLOCAR LOS CAMPOS EN NULL PARA VOLVER A INGRESAR DATOS

                    }
                }
                else{ //CONDICION POR SI NO SE CUMPLE LA VALIDACION DEL TELEFONO
                    JOptionPane.showMessageDialog(this, "Telefono Invalido"); //MENSAJE DE TELEFONO INVALIDO CUANDO LA VALIDACION NO SE CUMPLE
                }
            }
            else{ //CONDICION POR SI NO SE CUMPLE LA VALIDACION DE CORREO
                JOptionPane.showMessageDialog(this, "Correo Invalido"); //MENSAJE DE CORREO INVALIDO CUANDO LA VALIDACION NO SE CUMPLE
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Buscar_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_modificarMousePressed

    private void dtclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtclientesMouseClicked
    
    }//GEN-LAST:event_dtclientesMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(dtclientes.getSelectedRow()>=0 ){
            doc_cliente_txt.setText(String.valueOf(Long.parseLong(dtclientes.getValueAt(dtclientes.getSelectedRow(), 0).toString())));
            doc_cliente_txt.setForeground(Color.black);
            this.dispose();
        }else{
            int rpta = JOptionPane.showConfirmDialog(this, "NO A ELEJIDO NINGÚN CLIENTE, ¿DESEAS CERRAR LA BUSQUEDA RAPIDA?","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
            if(rpta == JOptionPane.YES_OPTION){
                this.dispose();
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel agregar;
    private javax.swing.JPanel buscar;
    private javax.swing.JTextField buscar2;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button15;
    private javax.swing.JPanel button3;
    private javax.swing.JPanel button4;
    private javax.swing.JPanel button5;
    private javax.swing.JPanel button6;
    private javax.swing.JPanel button7;
    private javax.swing.JTextField cedula_cliente;
    private javax.swing.JTextField correo_cliente;
    private javax.swing.JTextField direccion_cliente;
    public static javax.swing.JTable dtclientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel modificar;
    private javax.swing.JTextField papellido_cliente;
    private javax.swing.JTextField pnombre_cliente;
    private javax.swing.JTextField sapellido_cliente;
    private javax.swing.JTextField snombre_cliente;
    private javax.swing.JTextField telefono_cliente;
    // End of variables declaration//GEN-END:variables
}
