/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.usuariovista.usuario;
import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio
 */
public class Venta extends javax.swing.JPanel {

    private DefaultTableModel model;
    public static java.util.Date hoy = new java.util.Date();
    public static String patron = "dd/MMM/yyyy";

    public static String sfecha;
    public static DateFormat formato1;

    public Insets insets() {
        return super.insets(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * Creates new form Principal
     */
    public Venta() throws Exception {
        initComponents();
        cedula.setText(String.valueOf(Long.parseLong(usuario.getText())));
        Hilo_Lee h = new Hilo_Lee();
        h.inicio();
        fecha_venta.setText(fecha());
        //--------------------------------------------------
        //TABLA
        String data3[][] = {};
        String col[] = {"Cod Producto", "Nombre", "Descripcion", "Cantidad", "Precio", "Total"};
        model = new DefaultTableModel(data3, col);
        lista_articulos_table.setModel(model);

        //--------------------------------------------------
        //CAMPOS NO EDITABLES
        
        
        
        id_producto_txt.setEnabled(true);
        cantidad_producto_txt.setEnabled(true);

    }
public static String fecha(){
        Date fecha= new Date();
        SimpleDateFormat formatofecha=new SimpleDateFormat ("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    public class Hilo_Lee implements Runnable {

        Thread hilo;

        Conexion con;

        public Hilo_Lee() {
        }

        public void inicio() throws Exception {
            con = new Conexion();
            con.ConexionPostgres();

            if (hilo == null) {
                hilo = new Thread(this);//crea el hilo
                //	hilo=new Thread();//crea el hilo
                hilo.start();// lanzar el hilo

            }

        }

        public void stop() {
            hilo = null;
        }

        public void run() {
            String query = "";

            Thread hiloActual = Thread.currentThread();

            while (hilo == hiloActual) {
                try {
                    query = "select max(id_venta) from venta";
                    java.sql.ResultSet rs = con.consultar(query);
                    try {
                        if (rs.next()) {

                            int id = rs.getInt(1) + 1;
                            String idv = String.valueOf(id);
                            id_venta.setText(idv);

                        }
                    } catch (SQLException e) {
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Hilo_Lee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        public void pausa(int tiempo) {
            try {
                Thread.sleep(tiempo);
            } catch (InterruptedException ignorada) {
            }
        }

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        clientetxt = new javax.swing.JLabel();
        doc_cliente_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_articulos_table = new javax.swing.JTable();
        cedula = new javax.swing.JLabel();
        nuevaventa_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_venta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        valor_total = new javax.swing.JLabel();
        id_producto_txt = new javax.swing.JTextField();
        cantidad_producto_txt = new javax.swing.JTextField();
        elm = new javax.swing.JLabel();
        facturar = new javax.swing.JButton();
        agg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha_venta = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bsc_p = new javax.swing.JLabel();
        bsc_c = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        clientetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientetxt.setText("CLIENTE");
        add(clientetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        doc_cliente_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doc_cliente_txt.setForeground(new java.awt.Color(204, 204, 204));
        doc_cliente_txt.setText("cedula del cliente");
        add(doc_cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 182, -1));

        lista_articulos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod del Articulo", "Nombre", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lista_articulos_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 720, 260));

        cedula.setText("jLabel");
        add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 150, 20));

        nuevaventa_btn.setText("Nueva Venta");
        nuevaventa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaventa_btnActionPerformed(evt);
            }
        });
        add(nuevaventa_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 110, -1));

        jLabel1.setText("FACTURA No.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        id_venta.setText("jLabel2");
        add(id_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, 20));

        jLabel3.setText("cod producto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 730, 10));

        jLabel4.setText("cantidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 20));

        valor_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor_total.setText("0.0");
        add(valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 80, -1));
        add(id_producto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));
        add(cantidad_producto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 70, -1));

        elm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_producto.png"))); // NOI18N
        elm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elmMouseClicked(evt);
            }
        });
        add(elm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        facturar.setMnemonic('f');
        facturar.setText("Facturar");
        facturar.setToolTipText("");
        facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarActionPerformed(evt);
            }
        });
        add(facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 100, -1));

        agg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_agregar_producto .png"))); // NOI18N
        agg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aggMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aggMousePressed(evt);
            }
        });
        add(agg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jLabel2.setText("FECHA VENTA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 90, 20));

        fecha_venta.setText("jLabel7");
        add(fecha_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 180, 20));

        jLabel7.setText("VENDEDOR");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, 20));

        jLabel8.setText("Total");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 40, -1));

        bsc_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bsc_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsc_pMouseClicked(evt);
            }
        });
        add(bsc_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 40, 40));

        bsc_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        bsc_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsc_cMouseClicked(evt);
            }
        });
        add(bsc_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaventa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaventa_btnActionPerformed
        // TODO add your handling code here
        try {
        Venta.Hilo_Lee hl=new Venta.Hilo_Lee();
        hl.inicio();
        
        
        
        DefaultTableModel tb = (DefaultTableModel) lista_articulos_table.getModel();
        int a = lista_articulos_table.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount()-1);
        }
        
        id_producto_txt.setText("Ingrese Id");
        cantidad_producto_txt.setText("Ingrese Cantidad");
        valor_total.setText("0.0");
        
        
        
        /*try {
        Conexion con = new Conexion();
        
        con.ConexionPostgres();
        String query = "select max(id_venta) from venta";
        java.sql.ResultSet rs =con.consultar(query);
        if (rs.next()){
        int id = rs.getInt(1) + 1;
        String idv = String.valueOf(id);
        id_venta.setText(idv);
        }
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    } catch (Exception ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_nuevaventa_btnActionPerformed

    private void elmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elmMouseClicked
        // TODO add your handling code here:
        if(lista_articulos_table.getSelectedRow()>=0){
    DefaultTableModel model =(DefaultTableModel)lista_articulos_table.getModel();
    int rpta = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el producto?","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
    if(rpta == JOptionPane.YES_OPTION){
    model.removeRow(lista_articulos_table.getSelectedRow());
}
}else{
    JOptionPane.showMessageDialog(this,"¡No ha seleccionado ningún producto!","SISTEMA",JOptionPane.WARNING_MESSAGE);
}
    
    int contar=lista_articulos_table.getRowCount();
            double suma=0;
            for(int i=0; i<contar;i++){
            suma=suma+Double.parseDouble(lista_articulos_table.getValueAt(i, 5).toString());
            String sum = Double.toString(suma);
            valor_total.setText(sum);
            
            }
            if(contar==0){
            valor_total.setText("0.0");
            }
    }//GEN-LAST:event_elmMouseClicked

    private void facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarActionPerformed
        // TODO add your handling code here:
        
        Facturar fac = new Facturar();
        fac.setSize(400, 400);
        fac.setLocation(0, 0);
        fac.setVisible(true);
        
        //INSERSION DE DATOS EN LA TABLA VENTA PARA REGISTRAR LA VENTA
//    double vueltos1=Double.parseDouble(recibe.getText().trim())-Double.parseDouble(valor_total.getText());      
//    vueltos.setText(String.valueOf(vueltos1));
            
    
            //------------------------------------------------------------------------
            //INHABILITACION DE LOS CAMPOS UNA VEZ FACTURADO
   
            
            //------------------------------------------------------------------------
            //CONFIRMACION DE LA VENTA

           
    }//GEN-LAST:event_facturarActionPerformed

    private void aggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aggMouseClicked
    try {
            if(id_producto_txt.getText().equals("Ingrese Id") || id_producto_txt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese el Id del Producto");
            }else if(cantidad_producto_txt.getText().equals("Ingrese Cantidad") || cantidad_producto_txt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese la Cantidad del Producto");
            }else{
            
            int con1 = 0;
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "select * from producto where id_producto = " + Long.parseLong(id_producto_txt.getText().trim());
            
            ResultSet rs = con.consultar(query);
            
            
           

            if (rs.next()) {  
                int cant = Integer.parseInt(cantidad_producto_txt.getText().trim());
                double val = rs.getDouble("valor_producto");
                double subt = val*cant;
                
                model.insertRow(con1,new Object[]{});
                
                model.setValueAt((id_producto_txt.getText().trim()), con1, 0);
                model.setValueAt((rs.getString("nombre_producto")),con1,1);
                model.setValueAt((rs.getString("descripcion_producto")),con1,2);
                model.setValueAt((cantidad_producto_txt.getText().trim()), con1, 3);                
                model.setValueAt(rs.getString("valor_producto"), con1, 4);
                model.setValueAt((subt), con1, 5);
                
                
            con1++;
                
            } else {
                JOptionPane.showMessageDialog(this, "No existe el Producto");
            }
            
            int contar=lista_articulos_table.getRowCount();
            double suma=0;
            for(int i=0; i<contar;i++){
            suma=suma+Double.parseDouble(lista_articulos_table.getValueAt(i, 5).toString());
            String sum = Double.toString(suma);
            valor_total.setText(sum);
            }
            
            cantidad_producto_txt.setText(null);
            id_producto_txt.setText(null);
            
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aggMouseClicked

    private void aggMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aggMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggMousePressed

    private void bsc_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsc_cMouseClicked
    Buscar_Cliente busquedaC = new Buscar_Cliente();
    busquedaC.setVisible(true);
    }//GEN-LAST:event_bsc_cMouseClicked

    private void bsc_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsc_pMouseClicked
    Buscar_Producto busquedaP = new Buscar_Producto();
    busquedaP.setVisible(true);
    }//GEN-LAST:event_bsc_pMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agg;
    private javax.swing.JPanel body;
    private javax.swing.JLabel bsc_c;
    private javax.swing.JLabel bsc_p;
    private javax.swing.JTextField cantidad_producto_txt;
    public static javax.swing.JLabel cedula;
    private javax.swing.JLabel clientetxt;
    public static javax.swing.JTextField doc_cliente_txt;
    private javax.swing.JLabel elm;
    private javax.swing.JButton facturar;
    public static javax.swing.JLabel fecha_venta;
    private javax.swing.JTextField id_producto_txt;
    public static javax.swing.JLabel id_venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable lista_articulos_table;
    private javax.swing.JButton nuevaventa_btn;
    public static javax.swing.JLabel valor_total;
    // End of variables declaration//GEN-END:variables
}
